config/routes.rb
Rails.application.routes.draw do
  get 'hello_world/index'
  # get 'pages/hello'
  # root 'pages#hello'
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  before_validation :set_default_counters
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes
  has_many :comments

  # title must not be blank
  validates :title, presence: true

  # title must not exceed 250 characters
  validates :title, length: { maximum: 250 }

  # CommentsCounter must be an integer greater than or equal to zero
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # LikesCounter must be an integer greater than or equal to zero
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  after_save :update_posts_counter

  private

  def set_default_counters
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: :author_id
  has_many :likes
  has_many :comments, foreign_key: :author_id

  # name must not be blank
  validates :name, presence: true

  # PostsCounter must be an integer greater than or equal to zero.
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  users = User.includes(:posts).limit(10)
  users.each do |user|
    user.posts.each do |post|
      puts post.title
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.first
  end
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user_and_post, only: %i[new create]

  def new
    store_referer
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @comment = @post.comments.build(comment_params.merge(author_id: current_user.id))

    if @comment.save
      flash[:success] = 'Comment saved successfully'
      redirect_back_or_default(user_post_comments_path(@user, @post))
    else
      flash.now[:error] = 'Error: Comment could not be saved'
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def set_user_and_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end

  def store_referer
    session[:referer] = request.referer
  end

  def redirect_back_or_default(default)
    redirect_to(session[:referer] || default)
    session.delete(:referer)
  end
end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = current_user.likes.new(post: @post)

    respond_to do |format|
      if @like.save
        format.html { redirect_to user_post_path(@post.author, @post), notice: 'Like was successfully created.' }
      else
        format.html { redirect_to user_post_path(@post.author, @post), alert: 'Failed to create like.' }
      end
    end
  end
end

app/controllers/pages_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = 'Post saved successfully'
      redirect_to user_posts_path(current_user)
    else
      flash.now[:error] = 'Error: Post could not be saved'
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_world_helper.rb
module HelloWorldHelper
end

app/helpers/like_helper.rb
module LikesHelper
end

app/helpers/likes_helpers.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h3 style="color: #336699; margin: 12px 50px">Create a new comment💬</h3>
<%= form_with model: [@user, @post, @comment], url: user_post_comments_path(@post.author, @post), method: :post do |f| %>
  <div class="inputs">
    <%= f.label :text, style: "font-weight: bold;" %>
    <%= f.text_area :text, style: "width: 230px; height: 80px; padding: 10px" %>
  </div>
  <div>
    <%= f.submit "Submit the comment💬", style: "background-color: #007BFF; margin: 10px 100px; color: #fff; padding: 10px 15px; border: none; border-radius: 5px;" %>
  </div>
<% end %>

app/views/hello_world/index.html.erb
<h1>List of all User First time</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/new.html.erb
<h3 style="color: #336699; margin: 12px">If you Like the post just Click the button 👍😍</h3>
<%= form_with model: [@user, @post, @like], url: user_post_likes_path(@user, @post), method: :post do |f| %>
  <div>
    <%= f.submit "👍 Like", style: "background-color: #007BFF; margin: 10px 110px; color: #fff; padding: 10px 15px; border: none; border-radius: 5px; cursor: pointer;" %>
  </div>
<% end %>

app/views/pages/hello.html.erb
<h1>hello nested</h1>
<p>nested home page</p>
  

app/views/posts/index.html.erb
<h1>Great Quote</h1>
<div class="container">
  <div class="user_info">
    <div class="img">
      <%= image_tag @user.photo, alt: "User Photo", class: "user-photo" %>
    </div>
    <div class="user">
      👤<h2><%= link_to @user.name, user_path(@user) %></h2>
      <p><strong>Number of Posts:📝</strong> <%= @user.posts.count %></p>
    </div>
  </div>

  <% @posts.each do |post| %>
    <div class="post">
      <h4>Post📝</h4>
      <p><%= post.text %></p>
      <p class="count">Comments:💬<%= post.comments.count %> | Likes:👍<%= post.likes.count %></p>
    </div>
      <div class="comments">
        <% post.five_most_recent_comments.each do |comment| %>
          <div class="comment">
          <p><%= link_to(comment.author&.name, user_path(comment.author)) if comment.author&.id %>: <%= comment.text %></p>
          </div>
        <% end %>
      </div>
  <% end %>

  <%= link_to 'Pagination', user_posts_path(@user), class: 'button' %>
  <%= link_to 'Create New Post 📝', new_user_post_path(@user), class: 'button' %> 
</div>

app/views/posts/new.html.erb
<h3 style="color: #336699; margin: 12px">Create a new post📝😍</h3>

<%= form_with model: [@user, @post], url: user_posts_path(@user), method: :post do |f| %>
  <div class="inputs">
    <%= f.label :title, style: "font-weight: bold;" %>
    <%= f.text_field :title, style: "padding: 10px;" %>
  </div>
  <br>
  <div class="inputs">
    <%= f.label :text, style: "font-weight: bold;" %>
    <%= f.text_area :text, style: "width: 190px; height: 80px; padding: 10px" %>
  </div>
  <div>
    <%= f.submit "Submit the post📝", style: "background-color: #33cc33; margin: 10px 100px; color: #fff; padding: 10px 15px; border: none; cursor: pointer;" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div class="flash <%= key %>">
      <%= value %>
    </div>
  <% end %>

  <div class="post">
    <h4>Post <%= @post.title %></h4>
    <p class="count">Comments:💬<%= @post.comments.count %> | Likes:📝<%= @post.likes.count %></p>
    <p><%= @post.text %></p>
  </div>

  <div class="comments">
    <% @post.comments.each do |comment| %>
      <div class="comment">
        <p><%= comment.author&.name %>: <%= comment.text %></p>
      </div>
    <% end %>
  </div>

  <%= link_to 'Create New Comment 💬', new_user_post_comment_path(@user, @post), class: 'button' %>
  <h3 style="color: #336699; margin: 12px 50px">Create a new comment💬</h3>
  <%= form_with url: user_post_likes_path(@user, @post), method: :post do |f| %>
  
    <div>
      <%= f.submit 'Like 👍', class: 'button'%>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>List of all User</h1>
<div class="container">
<% @users.each do |user| %>
  <div class="user_info">
    <div class="img">
    <%= image_tag user.photo, alt: "User Photo", class: "user-photo"%>
  </div>
  <div class="user">
    <h2><%= link_to user.name, user_path(user) %></h2>
    <p><strong>Number of Posts:</strong> <%= user.posts.count %></p>
  </div>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<h1>List of all User with Post</h1>
<div class="container">
  <div class="user_info">
    <div class="img">
      <%= image_tag @user.photo, alt: "User Photo", class: "user-photo"%>
    </div>
    <div class="user">
      <h2><%= @user.name %></h2>
      <p><strong>Number of Posts:</strong> <%= @user.posts.count %></p>
    </div>
  </div>
  <div class="user_bio">
    <p>Bio</p>
  <p><%= @user.bio %></p>
  </div>
  <% @user.three_recent_posts.each_with_index do |post, index| %>
  <div class="post">
    <h4>Post <%= index+1  %>: <%= link_to post.title, user_post_path(@user, post) %></h4>
    <p><%= post.text %></p>
    <p class="count">Comments: <%= post.comments.count %> | Likes: <%= post.likes.count %></p>
  </div>
<% end %>
  <%= link_to "See all posts", user_posts_path(@user), class: 'button' %>
</div>